[WIP] User 1
wafflestudio18-5/team8-server pull request #38
Opened 2020-12-27 02:09 UTC by elijah0430

-Add User & Profile related APIs

closes #13 
closes #14

2021-01-02 14:13 UTC, elijah0430 commented
제가 테스트는 아직 작성 중이어서 API위주로 봐주시면 감사하겠습니다..ㅠㅠ

2021-01-02 14:58 UTC, dodo4114 reviewed
첫 세 커밋은 합쳐주시면 감사하겠습니다.

2021-01-02 15:09 UTC, dodo4114 requested changes
커밋명은 대문자로 시작하는 명령형으로, 해당 커밋의 역할을 적어주시면 감사하겠습니다.
아쉽게도 커밋 별 역할을 잘 모르겠어서 코드 전체에 대해 리뷰 남기는 점 양해 바랍니다.
몇가지 변경 요구사항이 있습니다.

2021-01-02 15:09 UTC, callmejustdodo commented on podo_server/podo_server/settings.py
> +    "*"
모든 도메인에 대해 호스팅을 허용한 이유가 무엇인가요?

2021-01-02 15:09 UTC, dodo4114 commented on podo_server/podo_server/settings.py
> +            'NAME': 'podo_dbb',
오타가 난 것 같습니다. 지워주세요!

2021-01-02 15:09 UTC, dodo4114 commented on podo_server/user/serializer.py
> +class UserSerializer(serializers.ModelSerializer):
`UserSerializer`의 역할이 크지 않은 듯 합니다. 굳이 시리얼라이저로 할 필요가 있을까요? 그냥 views에서 User.objects로 바로 건드리면 안될까요?

2021-01-02 15:09 UTC, dodo4114 commented on podo_server/user/views.py
> +        new=False
`is_new = User.objects.get(username=username).exist()` 를 추천드립니다.
https://medium.com/@bdv111/django%EC%97%90%EC%84%9C-exists-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-b3af4d387930

2021-01-02 15:09 UTC, dodo4114 commented on podo_server/user/views.py
> +            if image!=None:
`if image:` 혹은 `if bool(image):`는 안되나요?

2021-01-02 15:27 UTC, elijah0430 commented on podo_server/user/views.py
> +            if image!=None:
더 나은 것 같습니다! 수정하겠습니다.

2021-01-02 15:29 UTC, elijah0430 commented on podo_server/user/views.py
> +        new=False
오 감사합니다! 수정하겠습니다.

2021-01-02 15:40 UTC, elijah0430 commented on podo_server/user/views.py
> +        new=False
is_new = User.objects.filter(username=username).exists()
로 수정하였습니다!

2021-01-02 15:40 UTC, elijah0430 commented on podo_server/user/serializer.py
> +class UserSerializer(serializers.ModelSerializer):
그렇네요.. 그렇게 하는 게 더 좋을 것 같습니다!

2021-01-02 15:45 UTC, elijah0430 commented on podo_server/podo_server/settings.py
> +            'NAME': 'podo_dbb',
데이터베이스 새로 팠을 때 바꾸고 실수로 안 지웠네요 ㄷㄷ 치명적인 실수 지적해주셔서 정말 감사합니다!

2021-01-02 15:46 UTC, elijah0430 commented on podo_server/podo_server/settings.py
> +    "*"
에러때문에 실험해볼 때 변경하고 안 지웠었네요.. 수정하겠습니다!

2021-01-02 15:47 UTC, elijah0430 commented on podo_server/podo_server/settings.py
> +    "*"
커밋이름이 그런 역할이었군요..  제 미숙함으로 인해 가독성이 낮은 코드 읽어가시면서 지적해주셔서 정말 감사합니다 ㅠㅠㅠ 말씀해주신 부분 반영하여 모두 수정했습니다!

2021-01-03 00:36 UTC, dodo4114 approved these changes
어제 말씀드린 사항들은 전부 수정된 것 같으니, 일단 합쳐보겠습니다.

2021-01-03 00:37 UTC, dodo4114 commented
오...근데 컨플릭트가 나네요...`git pull --rebase origin main`해서 다시 올려주시겠어요?

2021-01-03 00:57 UTC, dodo4114 commented
테스트가 fail이 났네요 ㅠㅜ 확인 부탁드립니다

2021-01-03 01:48 UTC, dodo4114 commented
이번엔 또 컨플릭이...

2021-01-03 02:38 UTC, merged

2021-01-03 02:41 UTC, elijah0430 commented
@dodo4114 감사합니다!!!

2021-01-03 09:12 UTC, dodo4114 commented on podo_server/user/tests_user.py
> +"""
이거 왜 """되어있죠...?ㅋㄱㅋㅋㄱㅋㄱㄱㅋ

2021-01-03 13:54 UTC, elijah0430 commented on podo_server/user/tests_user.py
> +"""
앗 제가 이때 테스트가 완성이 안 된 시점이라 에러가 떠서 커멘트로 바꿨던 흔적인 것 같습니다..!