[WIP] Create Product API
wafflestudio18-5/team8-server pull request #50
Opened 2021-01-03 14:50 UTC by elijah0430

ProductSerializer를 사용하고자 하는 부분이 있어서 해당 부분 이외의 부분만 완성해두었습니다. Product PR이 머지되면 리베이스해서 완성하도록 하겠습니다

2021-01-06 05:47 UTC, dodo4114 requested changes

2021-01-06 05:47 UTC, dodo4114 commented on podo_server/user/views.py
> +rom django.core.paginator import Paginator
오타났네용 from으로 고쳐주세요

2021-01-06 05:47 UTC, dodo4114 commented on podo_server/user/views.py
> +    def productlist(self, request):
이러면 api 모양이 user/productlist가 되는건가요?

2021-01-06 05:47 UTC, dodo4114 commented on podo_server/user/views.py
> +            product=Product.objects.filter(seller=profile, id=pk)
seller=profile로 할 이유가 없는 것 같습니다.

2021-01-06 05:49 UTC, dodo4114 commented on podo_server/user/views.py
> +            product=Product.objects.filter(seller=profile, id=pk)
따라서 user와 profile을 가져오는 저 262, 263 라인도 필요 없을 것 같습니다.

2021-01-06 06:19 UTC, elijah0430 commented on podo_server/user/views.py
> +    def productlist(self, request):
네 맞습니다!

2021-01-06 06:20 UTC, elijah0430 commented on podo_server/user/views.py
> +    def productlist(self, request):
원래 엔드포인트대로 하려니까 NestedRouter 모듈을 설치해야 한다고 하던데, 기능상 꼭 필요할 것 같지는 않아서 그냥 엔드포인트를 바꿨습니다

2021-01-06 06:20 UTC, elijah0430 commented on podo_server/user/views.py
> +rom django.core.paginator import Paginator
넵!

2021-01-06 06:20 UTC, dodo4114 commented on podo_server/user/views.py
> +    def productlist(self, request):
원래 user/product/면 list를 받기로 약속했던 것 같은데, 아닌가요?
맞다면 노션문서 해당 부분 수정해주시고(되어있나요?)  안드로이드 팀에도 알려주세요!

2021-01-06 06:20 UTC, dodo4114 commented on podo_server/user/views.py
> +    def productlist(self, request):
아아 그렇군요 ㅋㅋㅋㄱㅋ 넵넵

2021-01-06 06:22 UTC, elijah0430 commented on podo_server/user/views.py
> +            product=Product.objects.filter(seller=profile, id=pk)
아 그런데 현재 로그인한 유저의 product만 특정하기 위해서는 해당 쿼리 조건이 필요하지 않을까요? @dodo4114

2021-01-06 06:23 UTC, elijah0430 commented on podo_server/user/views.py
> +            product=Product.objects.filter(seller=profile, id=pk)
아니면 GET /product와 GET /user/product가 비슷해질 것 같아서 그랬습니다

2021-01-06 06:26 UTC, elijah0430 commented on podo_server/user/views.py
> +    def productlist(self, request):
아 맞네요..,. 준호님한테만 말하고 따로 안드로이드팀에 말씀을 안 드렸었네요.. 협업인데 이렇게 해서 죄송합니다!!ㅠㅠ

2021-01-06 06:29 UTC, dodo4114 commented on podo_server/user/views.py
> +            product=Product.objects.filter(seller=profile, id=pk)
음 GET /user/product/pk/가 필요한 일이 있나요? GET /user/productlist는 필요한데... pk는 굳이 필요하지 않은 것 아닌가요? 어차피 pk는 유일하니까...

2021-01-06 06:31 UTC, elijah0430 commented on podo_server/user/views.py
> +            product=Product.objects.filter(seller=profile, id=pk)
@dodo4114 아무 생각없이 했는데 생각해보니 그렇네요;;

2021-01-06 06:32 UTC, elijah0430 commented on podo_server/user/views.py
> +            product=Product.objects.filter(seller=profile, id=pk)
혹시 모르니 원래 역할 한 번 문서에서 확인해보고, 정말로 필요 없는 것 같으면 삭제하는 쪽으로 해도 될 것 같습니다 ㅋㅋ

2021-01-06 06:32 UTC, dodo4114 commented on podo_server/user/views.py
> +            product=Product.objects.filter(seller=profile, id=pk)
넵넵 좋습니다 ㅎㅎ

2021-01-06 19:55 UTC, elijah0430 commented on podo_server/user/views.py
> +            product=Product.objects.filter(seller=profile, id=pk)
@dodo4114 수정했으니 확인해주시면 감사하겠습니다!

2021-01-07 05:34 UTC, dodo4114 approved these changes
LGTM

2021-01-07 06:45 UTC, merged